language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install codecov wheel cmarkgfm
- pip install --upgrade pytest
script:
- python setup.py test
after_script:
- bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r reports/coverage.xml -l Python
- codecov
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "fS/gGBgoEca3F+khHdfe+wxtyA+oSewWkJ2ZskuVK1n4coghNI1WJRpNVcR3hQhA4kejys69Z6fBoLnQJC2Xut/4TPe2p46eg1zEeOQQ92SPWwEYL6Cg0zuiaFW9gIpk/avURoM/7j/oJyIFra0ziG0GVgi9nBAwwMr5nO2T3N8+kdwhn2EhJNry7JD+pE2NJmSixgHoRmF/5zP1JPEEqhVRZyApZE+g6QYgPmAKxZ1eEUhqYpB1OyToeJPS7DwQJh31dQlQ2pKCyb98yziWT92oFTpHdBYmlZGXj6yv0mARRoVZgufiWTRnRXFVAmoxMSFHZh5KpnzWEZGQ/XRuKahUtv9isdU44aY8qRFG+yJCHZ7SwzEQXcX7eUY0IuNEnID2tirb+/DWqSl0LltMPegN4ao8Ia3uJX17id3CCVHvEEHkGPMt1/4eM9UEH1QUA6e/8GFIR7tLcjhk/YRkHaY+YK2fd9iWhOIBLdbYVRV5nC4slJa8mTE0WGqqX0lVeRINnIU5vjfhbypLv1mPGdLXJmtKoLluc8X/f2Px8Z6eX6+TSGpCqNuvbgaH9QlklqzrttKldpKpS3qDmJHcAAxC3WxYcJVIWyIx2lYPmvmEhN6e9xer6KFu4/NxlusixE/uig9C2Zj6r+J84FFY4yYWk6TFi7ZUq2w1nfeAxU4="
  on:
    tags: true
    branch: master
    python: '3.7'
  distributions: register sdist bdist_wheel
